repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check # Ruff Linter
        name: Ruff Lint
      - id: ruff-format # Ruff Formatter Check
        name: Ruff Format Check
        args: [--check]
  - repo: local
    hooks:
      - id: ty-check
        name: Ty Check
        entry: uv run ty check
        language: unsupported
        types: [python]
      - id: import-linter
        name: Import Linter
        entry: uv run lint-imports
        language: unsupported
        types: [python]
        pass_filenames: false
